### ISSUE TITLE
Resource Type: 0x0000

### ISSUE THREAD

**Issue by 6dlz** [androguard/androguard#888] opened 2022-02-28 07:00 UTC
AXML file has an unusual resource type! Malware likes to to such stuff to anti androguard! But we try to parse it anyways. Resource Type: 0x0000

**Comment by totoag** [comment] 2022-06-30 19:31
Any file to checkout ?

**Comment by bsstudent23** [comment] 2022-08-16 05:24
this file  - https://www.virustotal.com/gui/file/a720d84205ac28d15c3681d62d767cdc636486e15ab6ddf775ccd46cc8801435

**Comment by erev0s** [comment] 2023-12-15 22:04
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Closed by erev0s** 2023-12-15 22:04 UTC
