### ISSUE TITLE
TAG_ANDROID method printing?

### ISSUE THREAD

**Issue by the-house** [androguard/androguard#320] opened 2017-09-12 17:16 UTC
How can I print the TAG_ANDROID for a method given that analysis.VMAnalysis() is no longer present?

Thank you.

**Comment by reox** [comment] 2017-09-12 17:45
analysis.VMAnalysis was renamed to analysis.Analysis.

hth!

**Comment by the-house** [comment] 2017-09-12 23:26
Thank you for the quick reply!  

I am still not seeing a way to get the tags as the analysis.Analysis object does not have get_methods() only get_method() which cannot call get_tags().  Thoughts?

**Comment by reox** [comment] 2017-09-14 04:13
I think I never used this feature in the old versions. Can you give me an example how it used to work and what the output was?

**Comment by reox** [comment] 2017-09-14 04:25
duplicate of #269, please put your information there.

**Closed by reox** 2017-09-14 04:25 UTC
Labels: bug, duplicate
