### ISSUE TITLE
DVM.py get_locals for static methods

### ISSUE THREAD

**Issue by GeniusPudding** [androguard/androguard#856] opened 2021-04-19 02:00 UTC
Hi, thanks for this project. I'm try to use this to static analysis apps
I found that the result of function 'get_locals' in dvm.py may not always correct.
This function counts local registers num by 'self.code.get_registers_size() - len(params) - 1'
The last term '-1' means the relative object stored in register p0 in smali bytecode format

However, static methods won't store object in p0,
so the count of local registers may be  'self.code.get_registers_size() - len(params)'  (when 'static' in get_access_flags_string)

Trying get_locals results in images below: 
<img width="761" alt="Screen Shot 2021-04-19 at 9 52 56 AM" src="https://user-images.githubusercontent.com/55935566/115171175-14b88200-a0f5-11eb-9ae7-30478aa2076c.png">
<img width="655" alt="Screen Shot 2021-04-19 at 9 52 41 AM" src="https://user-images.githubusercontent.com/55935566/115171171-11bd9180-a0f5-11eb-80ae-8008a7265555.png">

**Comment by erev0s** [comment] 2023-12-13 23:27
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Closed by erev0s** 2023-12-13 23:27 UTC
