### ISSUE TITLE
AttributeError: module 'IPython.utils.io' has no attribute 'stdout'

### ISSUE THREAD

**Issue by JentCastttttt** [androguard/androguard#887] opened 2022-02-09 11:31 UTC
Please remove this template if you only have a question or do not want to create a new issue.

### Describe what you wanted to do
This is error when I use androguard.

### Describe what actually happened
╰─○ androguard analyze
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File /opt/homebrew/bin/androguard:8, in <module>
      6 if __name__ == '__main__':
      7     sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
----> 8     sys.exit(entry_point())

File /opt/homebrew/lib/python3.9/site-packages/click/core.py:1128, in BaseCommand.__call__(self, *args, **kwargs)
   1126 def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:
   1127     """Alias for :meth:`main`."""
-> 1128     return self.main(*args, **kwargs)

File /opt/homebrew/lib/python3.9/site-packages/click/core.py:1053, in BaseCommand.main(self, args, prog_name, complete_var, standalone_mode, windows_expand_args, **extra)
   1051 try:
   1052     with self.make_context(prog_name, args, **extra) as ctx:
-> 1053         rv = self.invoke(ctx)
   1054         if not standalone_mode:
   1055             return rv

File /opt/homebrew/lib/python3.9/site-packages/click/core.py:1659, in MultiCommand.invoke(self, ctx)
   1657         sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
   1658         with sub_ctx:
-> 1659             return _process_result(sub_ctx.command.invoke(sub_ctx))
   1661 # In chain mode we create the contexts step by step, but after the
   1662 # base command has been invoked.  Because at that point we do not
   1663 # know the subcommands yet, the invoked subcommand attribute is
   1664 # set to ``*`` to inform the command that subcommands are executed
   1665 # but nothing else.
   1666 with ctx:

File /opt/homebrew/lib/python3.9/site-packages/click/core.py:1395, in Command.invoke(self, ctx)
   1392     echo(style(message, fg="red"), err=True)
   1394 if self.callback is not None:
-> 1395     return ctx.invoke(self.callback, **ctx.params)

File /opt/homebrew/lib/python3.9/site-packages/click/core.py:754, in Context.invoke(_Context__self, _Context__callback, *args, **kwargs)
    752 with augment_usage_errors(__self):
    753     with ctx:
--> 754         return __callback(*args, **kwargs)

File /opt/homebrew/lib/python3.9/site-packages/androguard/cli/entry_points.py:476, in analyze(session, apk)
    461 @entry_point.command()
    462 @click.option(
    463     '--session',
   (...)
    473 )
    474 def analyze(session, apk):
    475     """Open a IPython Shell and start reverse engineering."""
--> 476     androlyze_main(session, apk)

File /opt/homebrew/lib/python3.9/site-packages/androguard/cli/main.py:416, in androlyze_main(session, filename)
    413 ipshell = InteractiveShellEmbed(config=cfg, banner1="{} started"
    414                                 .format(_version_string))
    415 atexit.register(shutdown_hook)
--> 416 init_print_colors()
    417 ipshell()

File /opt/homebrew/lib/python3.9/site-packages/androguard/misc.py:18, in init_print_colors()
     16 from IPython.utils import coloransi, io
     17 androconf.default_colors(coloransi.TermColors)
---> 18 androconf.CONF["PRINT_FCT"] = io.stdout.write

AttributeError: module 'IPython.utils.io' has no attribute 'stdout'

### System Information
- Androguard Version: master
- Python Version: 3.9.10
- Operating System MacOS 12.2

**Comment by JmStefanAndroid** [comment] 2022-02-14 02:09
same error

**Comment by thisisnitish** [comment] 2022-02-23 12:23
same error. But I use for python 3.8.x. I guess in docs, they have mentioned python version 3.6.x. Also, I feel the documentation is not up to date.
Thanks

**Comment by Tohure** [comment] 2022-03-10 19:32
Same error with pip way install mode. I've installed from "Install from Source" and everything working. Mac Monterey. If you have a problem using in step: virtualenv -p python3 venv-androguard

try: python3 -m virtualenv -p python3 venv-androguard

works for me

**Comment by Aoa0** [comment] 2022-09-14 10:23
It's caused by the compatibility issues of IPython installed by python 3.8+. Use a lower version of IPython should fix it. Version 7.16.3 works for me.

**Comment by nick143007** [comment] 2022-10-17 06:09
> It's caused by the compatibility issues of IPython installed by python 3.8+. Use a lower version of IPython should fix it. Version 7.16.3 works for me.

it worked for me also

**Comment by itstartstosnow** [comment] 2023-02-15 06:27
> It's caused by the compatibility issues of IPython installed by python 3.8+. Use a lower version of IPython should fix it. Version 7.16.3 works for me.

Thanks Aoa0, I had the same problem and this version works

**Comment by erev0s** [comment] 2023-12-15 22:04
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Closed by erev0s** 2023-12-15 22:04 UTC
