### ISSUE TITLE
Error parsing APK name

### ISSUE THREAD

**Issue by Te-k** [androguard/androguard#1066] opened 2024-07-15 21:37 UTC
### Describe what you wanted to do

Trying to parse app information of [this APK](https://www.virustotal.com/gui/file/9d28938889b08bb17564dfaef98b8b38cb9691561d0a7cdfb37a7b651db50ef9). Androguard failed to get the app name with a ARSC parsing failure.

### Describe what actually happened

```py
Importing apks/com.google.android.carrierlocation.apk
Traceback (most recent call last):
  File "/home/XXX/.pyenv/versions/3.10.4/envs/default3/lib/python3.10/site-packages/androguard/core/apk/__init__.py", line 1598, in get_android_resources
    return self.arsc["resources.arsc"]
KeyError: 'resources.arsc'


    'app_name': apk.get_app_name(),
  File "/home/XX.pyenv/versions/3.10.4/envs/default3/lib/python3.10/site-packages/androguard/core/apk/__init__.py", line 527, in get_app_name
    res_parser = self.get_android_resources()
  File "/home/XXX/.pyenv/versions/3.10.4/envs/default3/lib/python3.10/site-packages/androguard/core/apk/__init__.py", line 1604, in get_android_resources
    self.arsc["resources.arsc"] = ARSCParser(self.zip.read("resources.arsc"))
  File "/home/XXX/.pyenv/versions/3.10.4/envs/default3/lib/python3.10/site-packages/androguard/core/axml/__init__.py", line 1517, in __init__
    ate = ARSCResTableEntry(self.buff, res_id, pc)
  File "/home/XXX/.pyenv/versions/3.10.4/envs/default3/lib/python3.10/site-packages/androguard/core/axml/__init__.py", line 2931, in __init__
    self.item = ARSCComplex(buff, parent)
  File "/home/XXX/.pyenv/versions/3.10.4/envs/default3/lib/python3.10/site-packages/androguard/core/axml/__init__.py", line 2989, in __init__
    self.items.append((unpack('<I', buff.read(4))[0], ARSCResStringPoolRef(buff, self.parent)))
struct.error: unpack requires a buffer of 4 bytes
```

### System Information

- Androguard Version: master
- Python Version: 3.10.4
- Operating System: debian

**Comment by erev0s** [comment] 2024-07-15 21:44
@Te-k is this a correct apk file that is working when you install it to a device?

**Comment by cryptax** [comment] 2024-07-18 09:26
I have the same problem with `a.get_app_name()` and `a.get_android_resources()` for this APK.

This is what we have in the `AndroidManifest.xml`:

```xml
<application android:allowBackup="true" android:appComponentFactory="androidx.core.app.CoreComponentFactory
" android:extractNativeLibs="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:
roundIcon="@mipmap/ic_launcher_round" android:supportsRtl="true" android:theme="@style/AppTheme">
```

So, the application name is taken from `@string/app_name`. The string is present in `./rest/values/strings.xml`:

```xml
strings.xml:    <string name="app_name">Carrier Location</string>
```

Thus the returned application name should have been *Carrier Location*.

In another application for which `a.get_app_name()` worked, I directly have the application name in the `AndroidManifest.xml`, so Androguard needs not go and fetch it from the resources.

Perhaps a bug in the part that fetches the resources? ... would explain also why it complains about `resources.arsc`. (NB. the file is fine, and present in the APK though).

**Comment by erev0s** [comment] 2024-07-18 14:13
Hi @Te-k and @cryptax 
I will take a deeper look in the weekend when I will hopefully have a bit more time but from a first glance the first `entryOffsets` entry of the first `ResTable_type` has an offset that surpasses the length of the file itself.

I dont want to get ahead of myself and assume that this is a new evasion vector but it might as well be :D

**Comment by erev0s** [comment] 2024-07-21 09:25
hi @cryptax and @Te-k 
it seems to be a matter of the `FLAG_OFFSET16` ([here](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/libs/androidfw/include/androidfw/ResourceTypes.h;l=1473;drc=442fcb158a5b2e23340b74ce2e29e5e1f5bf9d66;bpv=0;bpt=0)) from the ResTable_type and the flag `FLAG_COMPACT` ([here](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/libs/androidfw/include/androidfw/ResourceTypes.h;l=1549;drc=442fcb158a5b2e23340b74ce2e29e5e1f5bf9d66;bpv=0;bpt=0)) which were both introduced in 2022 and therefore there are not part of the existing parsing logic of androguard.

I pushed a quick (and dirty) approach in [this](https://github.com/androguard/androguard/blob/resources_flags/androguard/core/axml/__init__.py#L1546) branch that tries to tackle such cases BUT its not complete. Something is off with my approach based on the Android source and it keeps missing two bytes and falls [here](https://github.com/androguard/androguard/blob/resources_flags/androguard/core/axml/__init__.py#L1564)

I pushed it as maybe someone would like to give it a shot (maybe @obfusk), so this can serve as a starting point and it might be easier to proceed.

Unfortunately I do not have more time atm, but will circle back to it in the future. It seems a nice opportunity to properly rewrite some parts of the parsing logic for resources.

**Comment by obfusk** [comment] 2024-07-25 02:43
The occasional 2-byte difference you see seems likely to be 4-byte alignment of the start offset. I don't think entries with `FLAG_COMPLEX` are handled correctly though.

See https://android.googlesource.com/platform/frameworks/base/+/master/libs/androidfw/include/androidfw/ResourceTypes.h#1591

My implementation: https://github.com/obfusk/reproducible-apk-tools/commit/f8d68b6fe30c00b22ec29a34b6471a92fca8029f

**Comment by obfusk** [comment] 2024-07-25 20:54
Also, the [implementation for `FLAG_WEAK`](https://github.com/androguard/androguard/blob/master/androguard/core/axml/__init__.py#L1540) looks odd to me. I've seen nothing to suggest it affects parsing, just that weak values "can be overridden without warning or error".

**Comment by erev0s** [comment] 2024-11-23 14:51
@Te-k this should be fixed now.

**Closed** 2024-12-29 10:43 UTC
