### ISSUE TITLE
Question about the AST

### ISSUE THREAD

**Issue by evilpan** [androguard/androguard#871] opened 2021-07-21 09:48 UTC
Hello,

First of all, thanks for the great tool!

I was writing a static analysis tool using androguard, and trying to parse the builtin AST (i.e. `DvMethod.get_ast()`), but found it not easy to link between the source/smali and the AST.

I can use MethodAnalysis.get_xref_from() to find the exact smali line in the caller, and I can search for `MethodInvocation` node in the caller's AST, however I'm not sure about the relation between the two.

Maybe we could add an offset value in the AST array?  For example, change `['MethodInvocation', params, triple, name, False]` to `['MethodInvocation', params, triple, name, False, offset]`? which offset is the same as what the xref_from returns.

**Comment by erev0s** [comment] 2023-12-13 23:35
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Closed by erev0s** 2023-12-13 23:35 UTC
