### ISSUE TITLE
Probelm while analyzing an APK using Androguard GUI

### ISSUE THREAD

**Issue by swapna-nikale** [androguard/androguard#876] opened 2021-08-24 16:12 UTC
Hi, I was trying to analyze an APK using Androguard GUI but I couldn't do due to the error given below. There is no wrong with the APK file

└─$ androguard gui -i 3c81c9df7ce0f94918cd0b833b070dfbbceacf8688824afbc6344e975edfeb24.apk                                                                                                                                               2 ⨯
[INFO    ] androguard.apk: Starting analysis on AndroidManifest.xml
[INFO    ] androguard.apk: APK file was successfully validated!
[INFO    ] androguard.analysis: Adding DEX file version 35
[INFO    ] androguard.analysis: Reading bytecode took : 0min 00s
[INFO    ] androguard.analysis: End of creating cross references (XREF) run time: 0min 00s
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/androguard/gui/mainwindow.py", line 186, in loadedFile
    self.updateDockWithTree()
  File "/usr/lib/python3/dist-packages/androguard/gui/mainwindow.py", line 340, in updateDockWithTree
    self.tree.fill()
  File "/usr/lib/python3/dist-packages/androguard/gui/treewindow.py", line 40, in fill
    sig = Signature(c)
  File "/usr/lib/python3/dist-packages/androguard/gui/helpers.py", line 8, in __init__
    self.class_components = self.cls.name.strip('L').strip(';').split('/')
TypeError: a bytes-like object is required, not 'str'
zsh: abort      androguard gui -i 

- Androguard Version: 3.4.0a1
- Python Version: Python 2.7.18
- Operating System: Kali Linux

**Comment by erev0s** [comment] 2023-12-13 23:36
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Closed by erev0s** 2023-12-13 23:36 UTC
