### ISSUE TITLE
get_certificate_name_string results in error: 'Name' object is not iterable

### ISSUE THREAD

**Issue by wdormann** [androguard/androguard#534] opened 2018-06-25 18:47 UTC
### Describe what you wanted to do

- is this error specific to a single file?

Yes, the androsign.py script that comes with androguard.

- if possible give a minimal working example where the error happens

python androsign.py <apkname> -s

### Describe what you expected

Certificate details.

### Describe what actually happened

```
$ python3 androsign.py com.snapchat.android.apk -s
com.snapchat.android.apk, package: 'com.snapchat.android'
Is signed v1: True
Is signed v2: False
Found 1 unique certificates
Error in com.snapchat.android.apk
Traceback (most recent call last):
  File "androsign.py", line 57, in main
    print("Issuer:", get_certificate_name_string(x509_cert.issuer, short=True))
  File "/home/tapioca/.local/lib/python3.6/site-packages/androguard/util.py", line 49, in get_certificate_name_string
    return ", ".join(["{}={}".format(_.get(attr,(attr,attr))[0 if short else 1], name[attr]) for attr in name])
TypeError: 'Name' object is not iterable
```

### System Information

- Androguard Version: master
- Python Version: 3.6.5
- Operating System: Ubuntu 18.04.  Same behavior on Windows 10

### Further Log Files and Output

I'm trying to update a script that was written for an older androguard version.  Based on the release notes at https://github.com/androguard/androguard/releases/tag/v3.2.0 , androsign.py should be referred to as new syntax for working with asn1crypto.  However, the script androsign.py itself doesn't appear to work.

**Comment by wdormann** [comment] 2018-06-25 18:50
asn1crypto 0.24.0 is installed on both machines, if it matters.

**Comment by reox** [comment] 2018-06-26 16:22
Can you upload the APK file here?

**Comment by wdormann** [comment] 2018-06-26 17:01
The error occurs with every APK I've tried.  So pick whichever you like.

**Comment by reox** [comment] 2018-06-27 14:54
this is really weird... I tested here with 0237c3848e1ebb204e08c9223c72c8092d51272e on Windows 7, Python 3.6.4 :: Anaconda, Inc., asn1crypto (0.24.0) and I get this result:
```
$ python androsign.py -s D:\com.snapchat.android.apk
com.snapchat.android.apk, package: 'com.snapchat.android'
Is signed v1: True
Is signed v2: False
Found 1 unique certificates
Issuer: C=01, ST=California, L=Los Angeles, O=Snapchat, OU=Captain Captcha, CN=Daniel Smith
Subject: C=01, ST=California, L=Los Angeles, O=Snapchat, OU=Captain Captcha, CN=Daniel Smith
Serial Number: 0x504f0d1c
Hash Algorithm: sha1
Signature Algorithm: rsassa_pkcs1v15
Valid not before: 2012-09-11 10:06:20+00:00
Valid not after: 2040-01-28 10:06:20+00:00
sha1 49f6badb81d89a9e38d65de76f09355071bd67e7
```

I also tested on a fresh virtualenv with debian buster, androguard 3.2.0 release,
there it looks like this:
```
$ ./foobar/bin/androsign.py -s com.snapchat.android.apk
com.snapchat.android.apk, package: 'com.snapchat.android'
Is signed v1: True
Is signed v2: False
Found 1 unique certificates
Issuer: Common Name: Daniel Smith, Organizational Unit: Captain Captcha, Organization: Snapchat, Locality: Los Angeles, State/Province: California, Country: 01
Subject: Common Name: Daniel Smith, Organizational Unit: Captain Captcha, Organization: Snapchat, Locality: Los Angeles, State/Province: California, Country: 01
Serial Number: 0x504f0d1c
Hash Algorithm: sha1
Signature Algorithm: rsassa_pkcs1v15
Valid not before: 2012-09-11 10:06:20+00:00
Valid not after: 2040-01-28 10:06:20+00:00
sha1 49f6badb81d89a9e38d65de76f09355071bd67e7
```

Can you try the following please:
```
cd /some/tmp/folder
virtualenv -p python3 androguard_venv
source ./androguard_venv/bin/activate
pip install androguard
./androguard_venv/bin/androsign.py -s com.snapchat.android.apk
```
maybe this is caused by some partially installed python stuff... On my machine it works fine in a fresh virtualenv, so I suspect it should work for you too.

**Comment by wdormann** [comment] 2018-06-27 15:10
The pip-installed version of androguard works.  But the current git version does not.  If I compare the two, I see:

```
@@ -53,8 +54,8 @@
             for cert in certs:
                 if args.show:
                     x509_cert = x509.Certificate.load(cert)
-                    print("Issuer:", x509_cert.issuer.human_friendly)
-                    print("Subject:", x509_cert.subject.human_friendly)
+                    print("Issuer:", get_certificate_name_string(x509_cert.issuer, short=True))
+                    print("Subject:", get_certificate_name_string(x509_cert.subject, short=True))
                     print("Serial Number:", hex(x509_cert.serial_number))
                     print("Hash Algorithm:", x509_cert.hash_algo)
                     print("Signature Algorithm:", x509_cert.signature_algo)
@@ -76,4 +77,4 @@
```

The androguard 3.2.0 release notes points to https://github.com/androguard/androguard/blob/master/androsign.py#L55 as an example of how you get certificate details.   But that file does not appear to have this change:
https://github.com/androguard/androguard/commit/b348ff61d844a5fbae3d411b14aa77f9297e6a44#diff-1926ea27a658230f583479928ff5c8a0

If you attempt to use the androsign.py file that uses the new syntax that appears to be recommended, it doesn't seem to work.

**Comment by wdormann** [comment] 2018-06-27 15:14
Since the change that I linked to was made a day after the 3.2.0 release, maybe this is as simple as pointing to the [3.2.0-release version of androsign.py](https://github.com/androguard/androguard/blob/b6e556f19e88bbf3d43e266a8467d8e12f201102/androsign.py), rather than master?

**Comment by reox** [comment] 2018-06-27 15:24
okay I see what the confusion is! The version of master needs to be used with the same version of https://github.com/androguard/androguard/blob/master/androguard/util.py 
So If you are using master, right now, use the certficate processing as described in master.
Between 3.2.0 and master was a small change in the `get_certificate_name_string` function...

The link in the release description always points to master, which is wrong... I'll release a new version in the next days where all these bug fixes are included and fix the description then.

**Comment by reox** [comment] 2018-06-27 15:28
No, wait. You say that using 3.2.0 works but as soon as you use the master it does not? I need to set up the same environment as you have and test that...

**Comment by reox** [comment] 2018-06-27 15:31
okay I think I see the error... you say you are using master, but the error message from your first post tells me, that utils.py is not from master... it is the old version. So you have somehow the old version installed but using master for the script...

**Comment by wdormann** [comment] 2018-06-27 15:34
Right.  The situation is this:

- I have androguard installed via pip.  This gets me 3.2.0
- Looking at the androguard [3.2.0 release notes](https://github.com/androguard/androguard/releases/tag/v3.2.0), it says "Please consult the API of asn1crypto or [androsign.py](https://github.com/androguard/androguard/blob/master/androsign.py#L55) how to access certain information of the certificate!"
- When I clicked the link to androsign.py, I see code that doesn't work with 3.2.0

**Comment by reox** [comment] 2018-06-29 07:47
I added now some documentation for the certificate processing, which will be merged soon

**Closed** 2018-11-22 09:09 UTC
Labels: question
