### ISSUE TITLE
Permission information in Call Graph

### ISSUE THREAD

**Issue by AkshatSood** [androguard/androguard#848] opened 2021-03-13 20:11 UTC
Is there a way to retrieve information regarding the permissions accessed at each node of a call graph? 

I have been creating Call Graphs using the following command: 

`androguard cg application01.apk`

I realise that there is a way to create call graphs using the following implementation: 

```
from androguard.misc import AnalyzeAPK
a, d, dx = AnalyzeAPK("application01.apk")
dx.get_call_graph()
```
Are there any additional parameters that can be passed in either one of these implementations to obtain information about the permissions requested at each node of the call graph? 

Thank you

**Comment by erev0s** [comment] 2023-12-13 22:55
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Closed by erev0s** 2023-12-13 22:55 UTC
