### ISSUE TITLE
show permissions is not defined

### ISSUE THREAD

**Issue by zurerita** [androguard/androguard#882] opened 2021-10-12 11:44 UTC
Hi!

Im trying to use the function show_Permissions() but I receive:  show_permissions is not defined

![error](https://user-images.githubusercontent.com/55254981/136949999-c73c5dde-436e-4e4a-bc26-5092963c8e32.JPG)

Could you help me? I need to know where are used the permissions of the app.

Thanks!

**Comment by erev0s** [comment] 2023-12-13 23:38
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Closed by erev0s** 2023-12-13 23:38 UTC
