### ISSUE TITLE
Confusion about XREFs on classes

### ISSUE THREAD

**Issue by reox** [androguard/androguard#647] opened 2019-02-20 10:14 UTC
Today I looked a little bit deeper into xref creation.
I noticed, that there is some difference how xrefs are created on classes, this might be a bug...

First, there are xrefs produced on const-class and new-instance opcodes:

https://github.com/androguard/androguard/blob/79c4f750643e7a26c3b021536c1bab57dbc2e7bf/androguard/core/analysis/analysis.py#L1086-L1087

Second, there are xrefs produced for method calls:
https://github.com/androguard/androguard/blob/79c4f750643e7a26c3b021536c1bab57dbc2e7bf/androguard/core/analysis/analysis.py#L1114-L1115

But in the first place, the method item is in both cases the same. That means that one of them is actually wrong?

For example: If you have a new-instance call, then the xref_to contains the wrong information, as it does not contain the target method (as there is none) but the current method in which this call was created.
Only the xref_from contains the correct information, as it stores the target method in which the call was created.
Here is a random class I selected:
```
       0 (0x00000000) invoke-direct                  v2, Ljava/lang/Object;-><init>()V
       1 (0x00000006) new-instance                   v0, Ljava/util/ArrayList;
       2 (0x0000000a) invoke-direct                  v0, Ljava/util/ArrayList;-><init>()V
       3 (0x00000010) iput-object                    v0, v2, Lnet/vrallev/android/cat/CatLog;->mPrinters Ljava/util/List;
       4 (0x00000014) iget-object                    v0, v2, Lnet/vrallev/android/cat/CatLog;->mPrinters Ljava/util/List;
       5 (0x00000018) new-instance                   v1, Lnet/vrallev/android/cat/print/AndroidLog;
       6 (0x0000001c) invoke-direct                  v1, Lnet/vrallev/android/cat/print/AndroidLog;-><init>()V
       7 (0x00000022) invoke-interface               v0, v1, Ljava/util/List;->add(Ljava/lang/Object;)Z
       8 (0x00000028) return-void
```

you can see the new-instance to `ArrayList` but the xref_to looks like this:
```
Lnet/vrallev/android/cat/CatLog;
    Ljava/util/ArrayList;
        REF_NEW_INSTANCE I Lnet/vrallev/android/cat/CatLog;-><init>()V [access_flags=protected constructor] @ 0x3163d0
```

The class `CatLog` calls `new-instance java.util.ArrayList` but the target method is again `CatLog->init`.

But as `invoke-direct` is called afterwards, the correct xref is stored too.

The question is now: is this on purpose? What it the reason to have new-instance store the wrong method? Should we add a new flag for this case? for example at ref_items have it something different, so you can decide if this was a new-instance of const-class or a method call?

**Comment by reox** [comment] 2019-02-20 13:05
I tried to resolve this by changing the REF field: #648

actually, the xrefs on the class are not really needed, are they?

**Comment by kneep** [comment] 2019-02-27 02:28
I didn't notice that. I was used to checking the <init> method reference. Creating class references seems a duplicate of creating <init> method references?

**Comment by reox** [comment] 2019-02-27 09:46
I thought about it and it might be useful, for example if the type is casted or something... AFAIK you will not see a method reference there but simply the class type popping up.

But my idea would be to replace this with a more generic system of having some XREF class which contains the type of xref as well as the reference and the referrer and the offset. Not sure how useful this though...

**Comment by reox** [comment] 2019-09-03 07:24
In order to understand whats going on, I read the old Tainted code. I noticed the following flaw in the current design:

* The old Tainted would store two different types of method access: TAINTED_PACKAGE_CREATE (only opcode 0x22) and TAINTED_PACKAGE_CALL (only opcode 0x6e...0x72 and 0x74...0x78).
* right now we store the CREATE only in the ClassAnalysis xrefs and we store there the method which called the class: XREF_TO contains the called class as key and a list of (ref_type, calling method, offset) as value.
* CREATE also uses now opcode 0x1c (const_class)
* In the case of CALL, we store in the ClassAnalysis different information: Again, the called class is the key, but the values are a list of (ref_type, called method, offset).
* This means, we loose the information which method called! This can only be recovered by reading the MethodClassAnalysis and comparing the offsets

**Comment by reox** [comment] 2019-10-18 06:07
Just want to know, has anyone an idea what happens if `const-class` or `new-instance` is called?
Can you say that in those cases the `<clinit>` and `<init>` methods are called?

**Closed** 2021-01-12 13:39 UTC
Labels: help wanted, question
