### ISSUE TITLE
Can't save the session

### ISSUE THREAD

**Issue by amohar** [androguard/androguard#845] opened 2021-02-22 14:03 UTC
### Describe what you wanted to do
I wanted to save the default session with a single freshly analyzed apk

### Describe what you expected
I expected to find the session file in the current working directory

### Describe what actually happened
I got an exception in the screenshot:
![AndroguardProblem](https://user-images.githubusercontent.com/3844154/108717045-1b73b000-751d-11eb-9699-ef9d816ff10d.PNG)

### System Information

- Androguard Version: master (from 22.02.2021.)
- Python Version: 3.7.9
- Operating System: Windows 10 Enterprize

### Further Log Files and Output
The traceback I'm getting in text form:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
c:\users\amohar\source\repos\android-inspector\env\src\androguard\androguard\cli\main.py in <module>
----> 1 misc.get_default_session().save()

c:\users\amohar\source\repos\android-inspector\env\src\androguard\androguard\session.py in save(self, filename)
    133         Save the current session, see also :func:`~androguard.session.Save`.
    134         """
--> 135         return Save(self, filename)
    136 
    137     def _setup_objects(self):

c:\users\amohar\source\repos\android-inspector\env\src\androguard\androguard\session.py in Save(session, filename)
     57     try:
     58         with open(filename, "wb") as fd:
---> 59             pickle.dump(session, fd)
     60         saved = True
     61     except RecursionError:

TypeError: can't pickle module objects
```

### Further notes
I have also tried implementing my own saving using pickle, as described in the documentation [here](https://androguard.readthedocs.io/en/latest/intro/bulk.html) (I have also tried using dill, which is supposed to handle some of these issues, but it also didn't work). The previous issue doesn't happen with this approach, but for some reason, pickle halts my python app while saving without any reported errors and the file gets partially written. When I try to load using the code in the screenshot below I get the exception on the same screenshot:
![AndroguardProblem1](https://user-images.githubusercontent.com/3844154/108718495-c6389e00-751e-11eb-8446-a97598f87ac2.PNG)

**Comment by amohar** [comment] 2021-02-24 16:40
While the first issue (not being able to pickle the session) still persists, I noticed some additional behaviors with the problem described in the "Further Notes" section in the main description. I pinpointed a class from the apk which when decompiled with DAD reproduces the behavior (exits the Androguard without any warnings or errors) when I try to retrieve the decompiled source (I tried using methods `get_source()` and `get_source_ext()`, both with the same results). The class is named `Lcom/facebook/stetho/common/Util;`, I'll attach its smali to this post:
[Util.zip](https://github.com/androguard/androguard/files/6037462/Util.zip)

I'm not sure if this warrants another bug or not. Please let me know if it is so, and if additional info is required. Thanks!

**Comment by erev0s** [comment] 2023-12-13 22:54
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Closed by erev0s** 2023-12-13 22:54 UTC
