### ISSUE TITLE
mutf8.py decode error: StopIteration

### ISSUE THREAD

**Issue by evilpan** [androguard/androguard#874] opened 2021-08-12 13:44 UTC
Please remove this template if you only have a question or do not want to create a new issue.

### Describe what you wanted to do

get_strings of dex

- is this error specific to a single file?
- if possible give a minimal working example where the error happens

### Describe what you expected

get list of strings.

### Describe what actually happened

dx.get_stirngs() throws exception.

### System Information

- Androguard Version: master
- Python Version: 3.8.10
- Operating System: Ubuntu 20.04.3 LTS

### Further Log Files and Output

```
In [7]: dx.get_strings()
Out[7]: ---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/.local/lib/python3.8/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~/.local/lib/python3.8/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~/.local/lib/python3.8/site-packages/androguard/core/analysis/analysis.py in __repr__(self)
    772         # TODO should remove all chars that are not pleasent. e.g. newlines
    773         if len(self.get_value()) > 20:
--> 774             s = "'{}'...".format(self.get_value()[:20])
    775         else:
    776             s = "'{}'".format(self.get_value())

~/.local/lib/python3.8/site-packages/androguard/core/mutf8.py in __str__(self)
    176     def __str__(self):
    177         if not self.__decoded:
--> 178             self.__decoded = decode(self).encode('utf8', errors='backslashreplace').decode('utf8')
    179         return self.__decoded
    180 

~/.local/lib/python3.8/site-packages/androguard/core/mutf8.py in decode(b)
     20         elif x >> 4 == 0b1110:
     21             # 3 byte Multichar
---> 22             b2 = next(b)
     23             b3 = next(b)
     24             if b2 >> 6 != 0b10:

StopIteration: 
```

- please report logs, tracebacks and other useful information
- if possible report the files you tried to analyze!

**Comment by TkTech** [comment] 2021-09-10 05:15
Can you try it with this branch: https://github.com/androguard/androguard/pull/825

**Comment by erev0s** [comment] 2023-12-13 23:35
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Closed by erev0s** 2023-12-13 23:35 UTC
