### ISSUE TITLE
Error: struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by dobaniashish** [androguard/androguard#585] opened 2018-12-11 12:08 UTC
### Error when trying to get certificates

When I call a.get_certificates() I get this error `struct.error: unpack requires a buffer of 4 bytes` only with the Brawl Stars apk from apkpure 

### FIle
APK: Brawl Stars v14.34
Version Code: 26
URL: https://apkpure.com/brawl-stars/com.supercell.brawlstars

### System Information
- Androguard Version: 3.2.1
- Python Version: 3.6
- Operating System: CentOS 7/Windows 10

### Traceback:
> 
> File "analyze.py", line 37, in <module>
>     certs = a.get_certificates()
>   File "/usr/local/lib/python3.6/site-packages/androguard/core/bytecodes/apk.py", line 1279, in get_certificates
>     for x in self.get_certificates_v1() + self.get_certificates_v2():
>   File "/usr/local/lib/python3.6/site-packages/androguard/core/bytecodes/apk.py", line 1252, in get_certificates_v2
>     for cert in self.get_certificates_der_v2():
>   File "/usr/local/lib/python3.6/site-packages/androguard/core/bytecodes/apk.py", line 1227, in get_certificates_der_v2
>     len_certs, = unpack('<I', block.read(4))
> struct.error: unpack requires a buffer of 4 bytes

**Comment by reox** [comment] 2018-12-11 13:08
It looks like this one is broken:
```
$ apksigner verify -verbose "Brawl Stars_v14.34_apkpure.com.apk"
DOES NOT VERIFY
ERROR: APK Signature Scheme v2 signer #1: Malformed additional attribute #1
```

probably need some more sanity checks in the code.

**Comment by dobaniashish** [comment] 2018-12-11 13:39
Here's another apk that got same error from both the sources.

Google Opinion Rewards
Version Code: 2018071785
URL: https://play.google.com/store/apps/details?id=com.google.android.apps.paidtasks
URL: https://apkpure.com/google-opinion-rewards/com.google.android.apps.paidtasks

**Comment by reox** [comment] 2018-12-11 13:45
mhh interesting, I tested with apksigner from API 28.0.3. Were there some changes to the v2 protocol?

**Comment by dobaniashish** [comment] 2018-12-12 11:12
Found proper result with keytool

> PS C:\Program Files\Java\jre1.8.0_131\bin> .\keytool -list -printcert -jarfile "F:\Google Opinion Rewards_v2018090624_apkpure.com.apk"
> Signer #1:
> 
> Signature:
> 
> Owner: CN=Unknown, OU="Google, Inc", O="Google, Inc", L=Mountain View, ST=CA, C=US
> Issuer: CN=Unknown, OU="Google, Inc", O="Google, Inc", L=Mountain View, ST=CA, C=US
> Serial number: 4934987e
> Valid from: Tue Dec 02 07:37:58 IST 2008 until: Sat Apr 19 07:37:58 IST 2036
> Certificate fingerprints:
>          MD5:  D0:46:FC:5D:1F:C3:CD:0E:57:C5:44:40:97:CD:54:49
>          SHA1: 24:BB:24:C0:5E:47:E0:AE:FA:68:A5:8A:76:61:79:D9:B6:13:A6:00
>          SHA256: 3D:7A:12:23:01:9A:A3:9D:9E:A0:E3:43:6A:B7:C0:89:6B:FB:4F:B6:79:F4:DE:5F:E7:C2:3F:32:6C:8F:99:4A
>          Signature algorithm name: MD5withRSA
>          Version: 1

Were there some changes to the v2 protocol?
I dont know if there were any changes.

**Comment by reox** [comment] 2018-12-12 11:37
keytool only reads v1 signatures.

**Comment by reox** [comment] 2018-12-18 08:04
Is it possible that these APKs are Signed with v3? I checked now the v1v2v3 Apks from the official testset, and they give me the same verify error in apksigner.
Looks like you can not use the version from API 28 anymore.

Can you test with the new v3 signing code from #587 ?

**Comment by dobaniashish** [comment] 2018-12-18 14:42
I checked with the latest commit on #587 and the error was gone.

**Comment by reox** [comment] 2018-12-18 14:44
okay nice, so we know that these are v3 signed.

the problem is, that the google tools do not work yet. I checked in the git history, and the changes that include v3 signing are not in the current version...

**Closed** 2018-12-19 18:05 UTC
Labels: bug
