### ISSUE TITLE
Instruction output for const-strings is weird/wrong.

### ISSUE THREAD

**Issue by eybisi** [androguard/androguard#977] opened 2023-12-24 12:36 UTC
I am using following function to get smali represantation of a encoded method.
```python
    def get_smali(target_method: EncodedMethod) -> str:
        """
        Get smali represantation of target_method
        """
        smali_str = ""
        for ins in target_method.get_instructions():
            smali_str += f"{ins.get_name()} {ins.get_output()}\n"
        return smali_str
  ```
  
  Now for const-string operation I get following outputs for different androguard versions:
  v3.3.5 = `const-string v14, "wcecvpfgu/ushdaiusyjr"`
  v3.4.0a1 = `const-string v14, 'wcecvpfgu/ushdaiusyjr'`
  v4.0.1 = `const-string v14, "'wcecvpfgu/ushdaiusyjr'"`
  
  Is this intented output for version v4.0.1 ?

**Comment by eybisi** [comment] 2023-12-26 09:42
Extra `"` comes from [here](https://github.com/androguard/androguard/blob/master/androguard/core/dex/__init__.py#L4983). Introduced in [commit](https://github.com/androguard/androguard/commit/2235d082a81557f5074fcef9eae7f2dc0d73c890#diff-07746d69911bf302deee8dc3f9e5343f867a3f4209f745d39818a655c5df215fR4809). Kind.String is already handled in earlier get_kind [function](https://github.com/androguard/androguard/blob/69ad51cc1c140c452a51b5b03362964e291dfbb3/androguard/core/dex/__init__.py#L4204) and returns inside of single quotes `'{}'`

Should I PR the removal of second Kind.String handling ?

**Comment by erev0s** [comment] 2023-12-26 10:46
hey @eybisi first of all thank you for taking a shot to resolve this, really appreciated.
I took a look as well and it was a tricky situation. The root cause was [this commit](https://github.com/androguard/androguard/commit/8df1fe850d21c74c4439940075ff1e9dc34274fc#diff-4bcfadb07d0bf1a1ec925cf35c112b8b49694235254b9ed7174819211ae1d5a2) and specifically [this](https://github.com/androguard/androguard/blob/master/androguard/core/dex/__init__.py#L2019) line is causing the issue.

This commit removed the internal mutf8 implementation that was available till that point and used the already existing pip package `mutf8`. This resulted in the `cm.get_string(value)` [here](https://github.com/androguard/androguard/blob/master/androguard/core/dex/__init__.py#L4204) already returning a string object and then calling `repr` on that string object. The call of `repr` on the string creates the double quotes. It seems `repr` is no longer required there. I will verify that the removal of `repr` does not create any other issues and commit this.

**Comment by erev0s** [comment] 2023-12-26 13:20
@eybisi please verify on your side as well that https://github.com/androguard/androguard/tree/977 fixes the issue and I will merge it.

**Comment by eybisi** [comment] 2023-12-27 09:52
Yes it fixes!

**Comment by erev0s** [comment] 2023-12-28 12:35
@eybisi  perfect, i will close this then.
Keep up the awesome work you do with your project.

**Closed by erev0s** 2023-12-28 12:35 UTC
