### ISSUE TITLE
--silent option not working properly causes errno 36 file name too long on terminal

### ISSUE THREAD

**Issue by alvaara** [androguard/androguard#744] opened 2019-10-14 01:41 UTC
I wanted to do decompile an apk file

- is this error specific to a single file?
apparently it will happen whenever a file's name is too long OR it is nested deep

- if possible give a minimal working example where the error happens

setting --silent option like: 
androguard --silent decompile app.apk --output ./outputdir

### Describe what you expected

not expected to ocurr when --silent is set

### Describe what actually happened
Androguard runs silently but starts echoing logs after a while

### System Information

- Androguard Version: 
`androguard --version`
> androguard, version 3.3.5

- Python Version: 2.7 (from error log below)
- Operating System
`uname -r`

> 4.19.0-kali5-amd64

`uname -a`

> Linux device_name 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-6kali1 (2019-07-22) x86_64 GNU/Linux

`cat /proc/version`

> Linux version 4.19.0-kali5-amd64 (devel@kali.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.37-6kali1 (2019-07-22)

###Output

everything runs smooth and goes on dumping until the error appears as:

>  File "/usr/local/bin/androguard", line 10, in <module>
>     sys.exit(entry_point())
>   File "/usr/lib/**python2.7**/dist-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/androguard/cli/entry_points.py", line 395, in decompile
>     jar, decompiler, format_)
>   File "/usr/local/lib/_python2.7_/dist-packages/androguard/cli/main.py", line 275, in export_apps_to_format
>     with open(filename + ".ag", "w") as fd:
> IOError: [Errno 36] File name too long: u'**./outputdir/nine/subdirs/deep/** buildFeedbackEvent (String String String D D String String I I I Date String [Location [Location I I I String String String String Z String String String I I String String String String String String String String String I I I I I I)Hashtable.ag'

**Comment by alvaara** [comment] 2019-10-14 01:45
also, I noticed the issue submit template mentions python3.x so I updated after this ticket was sent just in case

**Comment by reox** [comment] 2019-10-14 07:40
Are you using python3 or python2?

Regardless of that, the filename is too long to be stored on disk, hence the error message...
There are similar issues on windows with forbidden characters and so on... Probably we need some better way of storing the filenames. But I'm unsure how this should look like.
Hashes probably work but are crap to work with as a human, condensing the name might lead to errors if the method is overloaded etc... Anyone has a proposal?

**Comment by krnick** [comment] 2019-10-14 14:55
Hello @reox,

Just saw this issue, I have some idea but I don't know it would be a better solution.

1. use the hard link to operate the file.

2. copy the content to the temporary file, delete the temporary file after using it.

**Comment by reox** [comment] 2019-10-14 15:15
Hard links (also softlinks) sounds like a neat idea! But i think filename conditions like length etc also apply for them.
Also it will not work on windows as it has some weird system for links (requiring admin rights and stuff...)

**Comment by krnick** [comment] 2019-10-14 15:24
It seems that it is impossible to keep such as too-long function name as a filename since it will still be limited by the operating system's limitation such as allowable characters in the directory entries, length of the file name, length of the pathname and so on.

**Comment by krnick** [comment] 2019-10-14 15:27
sorry about accidentally delete the previous response :sweat:

**Comment by krnick** [comment] 2019-10-14 15:32
I think the only way to deal with the problem is to inform users not to use such long names or some not allowable characters through catch error?

**Comment by alvaara** [comment] 2019-10-14 16:01
Hi, thank you guys for the quick response. I am using python 2.7 btw. Would using python3 help?

Hope there is some kind of workaround even if its jus a sneaky trick. Perhaps running androguard in background could make things happen?

Thanks again for the fast response

**Comment by reox** [comment] 2019-10-14 16:52
Py3 will probably dont make a differnece but androguard will drop py2 support - as py2 itself is EOL ;)

**Comment by alvaara** [comment] 2019-10-15 13:04
I see, I will try with py3 just in case. Can you tell me how to make androguard use py3 instead of py2? 
I installed python3 but it uses py2 regardless.

**Comment by reox** [comment] 2019-10-15 13:06
probably because `which python` will return python2.

Have you installed it using `pip`? then you probably just need to use `pip3` instead.

**Comment by alvaara** [comment] 2019-10-15 18:40
> 
> 
> Are you using python3 or python2?
> 
> Regardless of that, the filename is too long **to be stored on disk**, hence the error message...
> There are similar issues on windows with forbidden characters and so on... Probably we need some better way of storing the filenames. But I'm unsure how this should look like.
> Hashes probably work but are crap to work with as a human, condensing the name might lead to errors if the method is overloaded etc... Anyone has a proposal?

Sorry, does that mean that I run out of space? like hd space? or memory space?

**Comment by reox** [comment] 2019-10-15 20:42
No. There are just limitations how long a filename might  be. These depend on the filesystem used.

**Comment by alvaara** [comment] 2019-10-17 16:53
I understand. I tried running androguard in background with '&' but it started logging anyways at some point. Thought that might help to know. Isn't it supposed to stay as a background process?

**Comment by krnick** [comment] 2019-10-18 01:21
you can add "2>&1 >/dev/null" to the end of your command.

**Comment by alvaara** [comment] 2019-10-21 19:54
Tried the command you suggested but it still logs the process. Then I tried the same with options --quiet and --silent added which did log less stuff, but still came to an errno 36.


![uplaod1](https://user-images.githubusercontent.com/9810587/67238330-5ba3b980-f423-11e9-8bf0-e420243efde7.png)

**Comment by krnick** [comment] 2019-10-22 00:34
The meaning of this command is to redirect the standard input/output/error to null in the situation of successful decompilation, but since your output is still due to the filename limitation problem, so this cannot be avoided

> So, I came to notice I've misunderstood the issue here, right? It is not a problem of echoing the name of the file, but the memory for storing a file with such a long string. Is it?

It is the file system limiting the length of the file name.

you could see the limitations on [wiki](https://en.wikipedia.org/wiki/Comparison_of_file_systems)

**Comment by reox** [comment] 2019-10-22 06:41
I pushed a fix to master. Can you test if this works for you?

**Closed** 2019-10-22 06:40 UTC
Labels: bug

**Comment by alvaara** [comment] 2019-10-26 00:24
I'm sorry, should I uninstall my current androguard version through pip and then reinstall it?

**Comment by alvaara** [comment] 2019-10-26 00:35
> The meaning of this command is to redirect the standard input/output/error to null in the situation of successful decompilation, but since your output is still due to the filename limitation problem, so this cannot be avoided
> 
> > So, I came to notice I've misunderstood the issue here, right? It is not a problem of echoing the name of the file, but the memory for storing a file with such a long string. Is it?
> 
> It is the file system limiting the length of the file name.
> 
> you could see the limitations on [wiki](https://en.wikipedia.org/wiki/Comparison_of_file_systems)

I see, thank you for the explanation!

**Comment by reox** [comment] 2019-10-26 08:15
You can upgrade it via pip:
```
pip install -U git+https://github.com/androguard/androguard 
```

**Comment by alvaara** [comment] 2019-10-28 00:51
Thank you @reox, pip3 did the trick. Upgraded my androguard installation and attempted to decompile my apk file successfully with no errors. So this seems to be fixed. Thank you so much!
