### ISSUE TITLE
How to generate call graph for thousands of APKs at a time

### ISSUE THREAD

**Issue by stu-sky** [androguard/androguard#860] opened 2021-05-29 08:31 UTC
Hi,

i want to extract call graphs of thousands of APks at a time.Now i know that i can use androguard cg  create a call graph from the docs.But for many APKs,does it mean I will repeat this command a thousand times?

So is there a more convenient way?I am an inexperienced rookie.I would be grateful for any good ideas or advice  of the problem

**Comment by totoag** [comment] 2022-06-30 19:37
Will be put that in the doc

**Comment by erev0s** [comment] 2023-12-13 23:31
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Closed by erev0s** 2023-12-13 23:31 UTC
