### ISSUE TITLE
'OSError: [Errno 2] "dot" not found in path' when using androdd.py

### ISSUE THREAD

**Issue by projectbtle** [androguard/androguard#584] opened 2018-12-06 05:02 UTC
Hello,

I'm trying to create the CFG for an APK in jpg/png format, but the androdd execution terminates with error.

```
C:\Users\XXX\.windows-build-tools\python27\Scripts\androdd.py --format jpg --output outimg testapp.apk
Dump information testapp.apk in outimg
Create directory outimg
Decompilation ... End
Dump La/a/a/a; <init> (La/a/a/c;)V ... jpg ... Traceback (most recent call last):
  File "C:\Users\XXX\.windows-build-tools\python27\Scripts\androdd.py", line 175, in <module>
    args.jar, args.decompiler, args.format)
  File "C:\Users\XXX\.windows-build-tools\python27\Scripts\androdd.py", line 109, in export_apps_to_format
    method2format(filename + "." + form, form, None, buff)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\androguard\core\bytecode.py", line 393, in method2format
    getattr(g, "write_" + _format.lower())(output)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1734, in new_method
    encoding=encoding)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1817, in write
    s = self.create(prog, format, encoding=encoding)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1922, in create
    raise OSError(*args)
OSError: [Errno 2] "dot" not found in path.
```

The same error is thrown when "png" is specified instead of "jpg". Three different real-world APKS were tested and all failed with the same error. No errors were thrown when androdd was run without the `--format` option.

I tried `pip install graphviz` and `pip install pydot`, but that made no difference (they were installed already).

**System Information:**
- Androguard Version: master (installed using `pip install -U androguard[magic,graphing,GUI]`)
- Python Version: 2.7
- OS: Windows

Any help would be appreciated.
Thank you.

**Comment by reox** [comment] 2018-12-06 10:23
You need to install the graphviz binaries as well and make sure they are in `%PATH%`.

**Comment by projectbtle** [comment] 2018-12-10 06:39
Thank you for the prompt response. 

Installing graphviz binaries did eliminate the issue, but I now get the following error:
```
Dump Landroid/support/v4/app/q; j ()Landroid/os/Parcelable; ... jpg ... Traceback (most recent call last):
  File "C:\Users\XXX\.windows-build-tools\python27\Scripts\androdd.py", line 175, in <module>
    args.jar, args.decompiler, args.format)
  File "C:\Users\XXX\.windows-build-tools\python27\Scripts\androdd.py", line 109, in export_apps_to_format
    method2format(filename + "." + form, form, None, buff)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\androguard\core\bytecode.py", line 393, in method2format
    getattr(g, "write_" + _format.lower())(output)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1734, in new_method
    encoding=encoding)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1817, in write
    s = self.create(prog, format, encoding=encoding)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1936, in create
    cmdline=cmdline,
NameError: global name 'cmdline' is not defined
```

However, this looks more like an issue with pydot.

**Comment by reox** [comment] 2018-12-11 08:18
might be the case, or androguard uses it wrong so it does not work with newer versions?

I have a working version here on Windows 7, pydot 1.2.4 and graphviz 2.34.0 (oh wow thats old).

I tested here with pydot 1.4.0 as well and get a similar error:
```
λ androdd.py --format jpg --output outimg tmp\Pkai.apk
Dump information tmp\Pkai.apk in outimg
Create directory outimg
Decompilation ... End
Dump Lorg/xdsb/xes/Din; <init> ()V ... jpg ... Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pydot.py", line 1915, in create
    working_dir=tmp_dir,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pydot.py", line 136, in call_graphviz
    **kwargs
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\androdd.py", line 175, in <module>
    args.jar, args.decompiler, args.format)
  File "C:\ProgramData\Anaconda3\Scripts\androdd.py", line 109, in export_apps_to_format
    method2format(filename + "." + form, form, None, buff)
  File "C:\ProgramData\Anaconda3\lib\site-packages\androguard\core\bytecode.py", line 393, in method2format
    getattr(g, "write_" + _format.lower())(output)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pydot.py", line 1734, in new_method
    encoding=encoding)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pydot.py", line 1817, in write
    s = self.create(prog, format, encoding=encoding)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pydot.py", line 1922, in create
    raise OSError(*args)
FileNotFoundError: [WinError 2] "dot" not found in path.
```

It is quite interesting, as pydot can find dot in 1.2.4... probably the best thing right now is to pin the version for pydot.

**Comment by projectbtle** [comment] 2018-12-19 13:02
After upgrading to pydot v1.4.1, the cmdline error is no longer present. 
Execution terminates with an AssertionError, though (but this also happens for pydot v1.2.4, so it's probably something wrong with some configuration on my end).

**Comment by reox** [comment] 2018-12-20 10:37
can you share the APK or is it for every APK?

**Comment by projectbtle** [comment] 2019-01-04 07:11
Apologies for the delay. I've tested it against 3 real-world apps and they all seem to have the problem.

```
Error: syntax error in line 8
...
<TR> ...
in label of node struct_754549e2184e641f42f7542a99e5bdff
Warning: node struct_754549e2184e641f42f7542a99e5bdff, port header unrecognized
Warning: node struct_754549e2184e641f42f7542a99e5bdff, port tail unrecognized

Traceback (most recent call last):
  File "C:\Users\XXX\.windows-build-tools\python27\Scripts\androdd.py", line 175, in <module>
    args.jar, args.decompiler, args.format)
  File "C:\Users\XXX\.windows-build-tools\python27\Scripts\androdd.py", line 109, in export_apps_to_format
    method2format(filename + "." + form, form, None, buff)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\androguard\core\bytecode.py", line 393, in method2format
    getattr(g, "write_" + _format.lower())(output)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1673, in new_method
    encoding=encoding)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1756, in write
    s = self.create(prog, format, encoding=encoding)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1884, in create
    assert p.returncode == 0, p.returncode
AssertionError: 1
```

The struct_xxxxxxxxxxxxxxxxxxxxxxxxxxx is different for each app (and appears to be the same for multiple runs against a single app).

**Comment by reox** [comment] 2019-01-04 08:46
this looks like a bug in pydot or a version incompatability between graphviz and pydot... can you again tell me which versions you use of pydot, graphviz and python? I can try to reproduce this issue.

maybe you can try to dump the raw dot file? Maybe the problem is visible then...
simply use `--format dot` to get the dot files.

I tested here with the following versions and it works:
* Windows 7 / python 3.6.4 / pydot 1.4.1 / graphviz 2.34.0 (20130907.0111)
* Debian stretch / python 3.5.3 / pydot 1.4.1 / graphviz 2.38.0 (20140413.2041)

**Comment by reox** [comment] 2019-01-04 10:07
I also tested with py2.7 and found a nasty bug (see #600) but it also works there with pydot 1.4.1 and graphviz 2.34.0...

Can you try with the APK in `examples/android/TestsAndroguard/bin/TestActivity.apk`?

**Comment by projectbtle** [comment] 2019-01-10 07:45
I'm testing with Windows 10 / python 2.7.13 / graphviz version 2.38.0 (20140413.2041) / pydot 1.4.1

The error is present with the test apk as well.  Attached is the dot output _[[outimgdottest.zip](https://github.com/androguard/androguard/files/2744110/outimgdottest.zip)]_, as well as the console output for `--format dot` _[[testdot.txt](https://github.com/androguard/androguard/files/2744116/testdot.txt)]_ and `--format jpg` _[[testjpgout.txt](https://github.com/androguard/androguard/files/2744117/testjpgout.txt)]_. The output files for `--format jpg` were 110 MB, and couldn't be uploaded.

In both cases, the execution crashed with 
```
Traceback (most recent call last):
  File "C:\Users\XXX\.windows-build-tools\python27\Scripts\androdd.py", line 175, in <module>
    args.jar, args.decompiler, args.format)
  File "C:\Users\XXX\.windows-build-tools\python27\Scripts\androdd.py", line 109, in export_apps_to_format
    method2format(filename + "." + form, form, None, buff)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\androguard\core\bytecode.py", line 393, in method2format
    getattr(g, "write_" + _format.lower())(output)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1734, in new_method
    encoding=encoding)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1817, in write
    s = self.create(prog, format, encoding=encoding)
  File "C:\Users\XXX\.windows-build-tools\python27\lib\site-packages\pydot.py", line 1945, in create
    assert process.returncode == 0, process.returncode
AssertionError: 1
```

Perhaps it's a combined effect of the specific Python and graphviz versions that I'm using (or some related configuration). I'll retest after downgrading graphviz, and also see if I can get another machine and try it with Python 3.

**Comment by reox** [comment] 2019-01-10 08:31
okay, so if the error occurs with the test APK, it is certainly either python, graphviz or pydot.

I also tested now with graphviz 2.38 on my windows 7 and it also works.

Can you try to update the python version to 2.7.15? Maybe pydot has some problems with 2.7.13.

**Comment by reox** [comment] 2019-01-10 10:50
So I tested this again and dumped the resulting buffer.
There is no difference between py2 and py3 (except for the colors) and it seems dot can directly read them without any problem

**Comment by projectbtle** [comment] 2019-01-22 14:11
Thanks so much for all the testing and for linking to pydot.
I haven't been able to re-test with other configs yet, but will update as soon as I am able.

**Comment by reox** [comment] 2019-09-25 17:20
So we know now why this fails. The problem is in pydot and with the HTML string that is passed to it.
Fixing this problem in androguard is quite hard, so I hope that it gets fixed in pydot soon :)
Until then, I made some refactoring in the method2dot function, which will hopefully circumvent this issue for now.

**Closed** 2019-10-22 07:09 UTC
Labels: bug, documentation, library
