### ISSUE TITLE
KeyError in bytecodes/dvm 

### ISSUE THREAD

**Issue by packmad** [androguard/androguard#703] opened 2019-05-28 16:01 UTC
### Describe what you wanted to do

I'm analyzing dex files extracted from Android ROMs.
I'm sure that they are valid dex files, I'm able to disassemble them with dexdump and jadx.
I often find files that trigger this exception:

```
File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 7326, in get_type_list
    i = self.__typelists_off[off]
```

- is this error specific to a single file? no

- a [minimal working example](https://www.dropbox.com/s/xh2wscwhhw22ojc/test.dex?dl=0) where the error happens.

### Further Log Files and Output
```
Traceback (most recent call last):
  File "/home/simo/gitProj/Test/cmp_class.py", line 27, in __init__
    self.digest = self.session.add(dex_file, fd.read())
  File "/usr/local/lib/python3.6/dist-packages/androguard/session.py", line 310, in add
    digest, _, _ = self.addDEX(filename, raw_data, dx)
  File "/usr/local/lib/python3.6/dist-packages/androguard/session.py", line 221, in addDEX
    d = DalvikVMFormat(data)
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 7643, in __init__
    self._load(buff)
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 7654, in _load
    self.map_list = MapList(self.CM, self.__header.map_off, self)
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 7540, in __init__
    mi.parse()
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 7053, in parse
    self.item = [AnnotationItem(buff, cm) for i in range(0, self.size)]
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 7053, in <listcomp>
    self.item = [AnnotationItem(buff, cm) for i in range(0, self.size)]
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 1696, in __init__
    self.annotation = EncodedAnnotation(buff, cm)
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 1630, in __init__
    self.elements.append(AnnotationElement(buff, cm))
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 1578, in __init__
    self.value = EncodedValue(buff, cm)
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 1493, in __init__
    self.value = cm.get_method(id)
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 7363, in get_method
    return method.get_list()
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 2506, in get_list
    return [self.get_class_name(), self.get_name(), self.get_proto()]
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 2472, in get_proto
    self.proto_idx_value = self.CM.get_proto(self.proto_idx)
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 7351, in get_proto
    return [proto.get_parameters_off_value(),
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 2146, in get_parameters_off_value
    params = self.CM.get_type_list(self.parameters_off)
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/dvm.py", line 7326, in get_type_list
    i = self.__typelists_off[off]
KeyError: 6958908
```

### System Information

- Androguard Version: 3.3.5
- Python Version: 3.6
- Operating System: Ubuntu 18.04 x64

### My code
I'm not using Androguard in the "standard" way, because I'm not analyzing APK files and I'm just interested in methods' opcodes.
This is my code (it always work with toys example, but often fails with big dex):
```
class AndroguardDexAnalysis:

    def __init__(self, dex_file: str):
        assert os.path.isfile(dex_file)
        self.clsname_to_class = {}
        self.session = session.Session()
        with open(dex_file, "rb") as fd:
            self.digest = self.session.add(dex_file, fd.read())  # EXCEPTION!
           
```

**Comment by reox** [comment] 2019-05-29 06:55
Can you upload such a dex file here?
and can you test with the latest master, maybe the problem is already fixed - the dex parsing was rewritten partially...

**Comment by reox** [comment] 2019-05-29 07:51
ah sorry, I did not saw that you attached the DEX. I'll have a look!

**Comment by reox** [comment] 2019-05-29 07:53
Might be related to DEX v039.

**Comment by reox** [comment] 2019-05-29 08:07
Can someone confirm my theory: The annotation_set_item in the map points to offset 6692366 in the file. The DEX documentation says, that the table is aligned by 4 bytes but this offset is not. It looks like the correct offset would be 6692368, which would then read an array size of 1 instead of 0x010000.

If I skip the two alignment bytes, it works... I guess we need to check if there are other structs in the file which need alignment!

**Comment by packmad** [comment] 2019-05-29 10:19
Your fix is also working in other cases!
Thank you.

**Comment by reox** [comment] 2019-05-29 10:39
nice! I merged it into master now!

**Closed** 2019-05-29 10:39 UTC
Labels: DEX Parser, bug
