### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_end'

### ISSUE THREAD

**Issue by IsaacTiger** [androguard/androguard#886] opened 2021-11-29 11:23 UTC
System Information
Androguard Version: androguard==3.3.5
Python Version: 3.8.6
Operating System: Windows

I want to estimate Apks' methods is null or not by calling get_source(). But sometimes when I calling this method, this bug occurs. Please tell me how to fix it.
![image](https://user-images.githubusercontent.com/38802197/143859239-0ce13302-d486-4166-9190-20d0c01ca123.png)

Result:
Traceback (most recent call last):
  File "c:/Users/Administrator/Desktop/Detection/Code_Dection/get_java_code.py", line 53, in get_java_code   
    if m.get_source() is not None:
  File "D:\python3.8.6\lib\site-packages\androguard\core\bytecodes\dvm.py", line 3064, in get_source
    return self.CM.decompiler_ob.get_source_method(self)
  File "D:\python3.8.6\lib\site-packages\androguard\decompiler\decompiler.py", line 575, in get_source_method
    z.process()
  File "D:\python3.8.6\lib\site-packages\androguard\decompiler\dad\decompile.py", line 180, in process
    identify_structures(graph, graph.immediate_dominators())
  File "D:\python3.8.6\lib\site-packages\androguard\decompiler\dad\control_flow.py", line 406, in identify_structures
    loop_struct(Gi, Li)
  File "D:\python3.8.6\lib\site-packages\androguard\decompiler\dad\control_flow.py", line 190, in loop_struct
    lnodes = mark_loop(first_graph, head, node, head.interval)
  File "D:\python3.8.6\lib\site-packages\androguard\decompiler\dad\control_flow.py", line 124, in mark_loop
    latch = end.get_end()
  File "D:\python3.8.6\lib\site-packages\androguard\decompiler\dad\node.py", line 156, in get_end
    return self.end.get_end()
AttributeError: 'NoneType' object has no attribute 'get_end'

**Comment by r1ght0us** [comment] 2022-05-05 17:20
@IsaacTiger  I also encountered this problem, did you solve it?

**Comment by IsaacTiger** [comment] 2022-05-06 02:23
> @IsaacTiger I also encountered this problem, did you solve it?

不好意思，时间隔得太久了，我也不太记得怎么搞的了。好像是重新配置了一遍环境，然后重新安装了Androguard还有相关的依赖才解决了这个问题

**Comment by erev0s** [comment] 2023-12-13 23:39
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Closed by erev0s** 2023-12-13 23:39 UTC
