### ISSUE TITLE
Call Graph creation using cg command

### ISSUE THREAD

**Issue by AkshatSood** [androguard/androguard#851] opened 2021-03-23 21:35 UTC
I have been creating Call Graphs for android APKs using the `cg` command listed in the [documentation](https://androguard.readthedocs.io/en/latest/tools/androcg.html). The usage of the command is as follows: 

`androguard cg sample_apk.apk`

This creates a ".gml" file for the call graph, with individual nodes looking like the following 

`node [
    id 7
    label "Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;-><clinit>()V [access_flags=static constructor] @ 0xb2e10"
    external 0
    entrypoint 0
  ]`

I had 2 questions regarding the call graph that is generated,

1. Is the label assigned here corresponding to the class name/method name? I tried using `dx.get_methods()` to generate a list of methods (along with class names and descriptors), but none of these methods were in the call graph for the same APK. 
2. Does this command create a call graph for the entire application?  

I would really appreciate some help with this, thanks!

**Comment by akashpatelcse** [comment] 2021-08-20 11:18
Have you found the solution @AkshatSood

**Comment by AkshatSood** [comment] 2021-08-23 09:10
> Have you found the solution @AkshatSood

Unfortunately, I was not able to find a clear answer to this. My best guess at the time is that the `cg` command is used to create call graphs which include methods from external libraries as well. I had to write a script to remove the external nodes (and corresponding edges), as the .gml file contains information about which nodes are external.

**Comment by erev0s** [comment] 2023-12-13 22:55
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Closed by erev0s** 2023-12-13 22:55 UTC
