### ISSUE TITLE
" OSError: [Errno 22] Invalid argument: " when using androdd.py

### ISSUE THREAD

**Issue by WadeaHijjawi** [androguard/androguard#342] opened 2017-11-08 11:15 UTC
First of all, thank you very much for solving #339 , but when I tried executing androdd.py tool to get the source code all the classes packaged in an APK file I have another error as following:
" OSError: [Errno 22] Invalid argument: " (the error details below)

I don't sure if that Python version error or Windows 10 error but please provide me if there any hint or solution for this problem.

### System Information

- Androguard Version: master
- Python Version: 3.6
- Operating System: Windows 10 64bit.

### Further Log Files and Output
E:\androguard>python androdd.py -i tv.peel.app.apk -o er
Dump information tv.peel.app.apk in er
Create directory er
Decompilation ... End
Dump La/a/a/a/a/a; <init> ()V ... source codes ... bytecodes ... Traceback (most recent call last):
  File "androdd.py", line 218, in <module>
    main(options, arguments)
  File "androdd.py", line 204, in main
    options.jar, options.decompiler, options.format)
  File "androdd.py", line 193, in export_apps_to_format
    with open(filename + ".ag", "w") as fd:
OSError: [Errno 22] Invalid argument: 'er/a/a/a/a/a/a/<init>--V.ag'

**Comment by reox** [comment] 2017-11-09 08:11
the problem is that the filename would contain invalid characters... A solution for this is not so straight forward, as there are so many versions how the name of a class can be messed up... And just replace all chars that are not allowed also does not help. :/

this is a duplicate of #130, closing this one

**Closed by reox** 2017-11-09 08:11 UTC
Labels: duplicate
