### ISSUE TITLE
Byte Code Error in androaxml.py with Python3

### ISSUE THREAD

**Issue by hassan-91** [androguard/androguard#550] opened 2018-08-10 15:35 UTC
Error: Byte Code Error 
```
Traceback (most recent call last):
  File "androguard/androaxml.py", line 85, in <module>
    main(options, arguments)
  File "androguard/androaxml.py", line 67, in main
    fd.write(buff)
  File "venvs_home/mob_test/lib/python3.5/codecs.py", line 718, in write
    return self.writer.write(data)
  File "venvs_home/mob_test/lib/python3.5/codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by reox** [comment] 2018-11-21 20:04
I remember I encountered this bug too, but can not reproduce it right now.
Either it was fixed by the changes recently or it occured only on certain samples.
@hassan-91 do you still have the sample where this happend?

**Comment by reox** [comment] 2018-12-30 18:08
I noticed that sometimes some encoding problems pop up while testing #592 
this seems to be some issue with python2.7 right now, not beeing able to handle non-ascii in piped streams for some reasons...

**Closed** 2019-01-03 10:08 UTC
Labels: bug
