### ISSUE TITLE
DalvikVMFormat: struct.error: unpack requires a buffer of 1 bytes

### ISSUE THREAD

**Issue by evilpan** [androguard/androguard#875] opened 2021-08-18 09:18 UTC
### Describe what you wanted to do

Parse a dex file with DalvikVMFormat class.

- is this error specific to a single file? maybe.

a minimal working example where the error happens:

poc.py
```py
#!/usr/bin/env python3
from androguard.core.bytecodes.dvm import DalvikVMFormat

with open('./classes.dex', 'rb') as f:
    dex = f.read()
df = DalvikVMFormat(dex, '29')
```

The dex file is in [dex.zip](https://github.com/androguard/androguard/files/7005996/dex.zip).

### Describe what you expected
Got a DalvikVMFormat instance.

### Describe what actually happened

```
$ ./poc.py
Traceback (most recent call last):
  File "/tmp/poc.py", line 6, in <module>
    df = DalvikVMFormat(dex, '29')
  File "/usr/local/lib/python3.9/site-packages/androguard/core/bytecodes/dvm.py", line 7674, in __init__
    self._load(buff)
  File "/usr/local/lib/python3.9/site-packages/androguard/core/bytecodes/dvm.py", line 7686, in _load
    self.map_list = MapList(self.CM, self.header.map_off, self)
  File "/usr/local/lib/python3.9/site-packages/androguard/core/bytecodes/dvm.py", line 7562, in __init__
    mi.parse()
  File "/usr/local/lib/python3.9/site-packages/androguard/core/bytecodes/dvm.py", line 7081, in parse
    self.item = [StringDataItem(buff, cm) for _ in range(self.size)]
  File "/usr/local/lib/python3.9/site-packages/androguard/core/bytecodes/dvm.py", line 7081, in <listcomp>
    self.item = [StringDataItem(buff, cm) for _ in range(self.size)]
  File "/usr/local/lib/python3.9/site-packages/androguard/core/bytecodes/dvm.py", line 1964, in __init__
    self.utf16_size = readuleb128(cm, buff)
  File "/usr/local/lib/python3.9/site-packages/androguard/core/bytecodes/dvm.py", line 220, in readuleb128
    result = get_byte(cm, buff)
  File "/usr/local/lib/python3.9/site-packages/androguard/core/bytecodes/dvm.py", line 210, in get_byte
    return cm.packer["B"].unpack(buff.read(1))[0]
struct.error: unpack requires a buffer of 1 bytes
```

### System Information

- Androguard Version: master
- Python Version: 3.4.0a1
- Operating System: Darwin iMac.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
- Python 3.9

**Comment by zhanghengtime** [comment] 2023-06-09 10:26
I also encountered this error and don't know how to solve it

**Comment by totoag** [comment] 2023-06-09 11:24
@zhanghengtime what is your dex file ? As this one in this issue seems ok now

**Comment by zhanghengtime** [comment] 2023-06-09 14:33
I did not have this issue in version 3.3.5, but it occurred in version 3.4.0 alpha1. I am not sure why， so could you please tell me what changes have been made between these two versions

**Comment by evilpan** [comment] 2023-06-10 02:25
@zhanghengtime Please attach your apk/dex file here so people can debug with it, we cannot tell anything just by an version number.

**Comment by zhanghengtime** [comment] 2023-06-11 04:42
Thanks for your answer, then I will study it myself, it is inconvenient to attach the dex file.

**Comment by erev0s** [comment] 2023-12-13 23:36
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.

**Closed by erev0s** 2023-12-13 23:36 UTC
