### ISSUE TITLE
No permission_xx.json when target sdk is larger than 25

### ISSUE THREAD

**Issue by kneep** [androguard/androguard#601] opened 2019-01-05 09:22 UTC
I tested an App which is targeted for sdk 26 and got a empty dict from get_requested_aosp_permissions.
Is there any plan to add newer permission_xx.json?

**Comment by reox** [comment] 2019-01-05 10:04
the permission mappings are generated by axplorer, but API level 25 is the newest available :(

duplicate of #576

**Closed by reox** 2019-01-05 10:04 UTC
Labels: duplicate

**Comment by kneep** [comment] 2019-01-06 14:34
I don't think get_requested_aosp_permissions has anything to do with the mappings. And I don't see any json files in axplorer. What aosp permissions an App requests can be simply inferred from the manifest file. It does make sense to check against the permission_module which is directly from permission_xx.json before returning the permissions. Missing such files would cause the routine to return an empty dict. So I was asking where these files came from to see if I can help.

BTW, axplorer seems not well maintained. So maybe a new way is needed.

**Comment by reox** [comment] 2019-01-06 14:48
the json files are generated with this script: https://github.com/androguard/androguard/blob/master/generators/axplorer_to_androguard.py

If you have a better source for those files, please share ;)
